import Head from "next/head";
import { Inter } from "next/font/google";
import { Button } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2>Welcome to Doc247 Components Library</h2>
        <Button variant="contained">Click</Button>
      </main>
    </>
  );
}
